config/routes.rb
Rails.application.routes.draw do
  get 'companies/index'
  get 'companies/show'
  get 'companies/crate'
  get 'companies/new'
  get 'companies/edit'
  get 'companies/update'

  get 'people/index'

  devise_for :admins, controllers: { registrations: "admins/registrations" }
  devise_for :companies
  devise_for :people
  resources :jobs

  get 'tags/:tag', to: 'people#index', as: :tag 

  match ':controller(/:action(/:id))', :via => :get

  root 'jobs#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
	belongs_to :company
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "600x600>", small: "200x200>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  acts_as_taggable

end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController
  # disable default no_authentication action
  skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
  # now we need admin to register new admin
  prepend_before_action :authenticate_scope!, only: [:new, :create, :cancel]

  protected

  def sign_up(resource_name, resoure)
    # just overwrite the default one
    # to prevent auto sign in as the new sign up
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permited_parameters, if: :devise_controller?

  protected

  def configure_permited_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  	devise_parameter_sanitizer.for(:sign_up) << :avatar
  	devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:sign_up) << :bio
    devise_parameter_sanitizer.for(:account_update) << :bio
    devise_parameter_sanitizer.for(:sign_up) << :tag_list
    devise_parameter_sanitizer.for(:account_update) << :tag_list
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @company_jobs = current_company.jobs
  end

  def show
  end

  def crate
  end

  def new
  end

  def edit
  end

  def update
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	before_action :find_jobs, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_company!, except: [:index, :show]

	def index
		@jobs = Job.all.order("created_at DESC")
		@category = Category.all
	end

	def show
	end

	def new
		@job = current_company.jobs.build
		#@job = current_user.job.build
	end

	def create
		@job = current_company.jobs.build(jobs_params)

		if @job.save
			redirect_to @job
		else 
			render "New"
		end
	end

	def edit
		
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else 
			render "New"
		end
	end

	def destroy
		@job.destroy
		redirect_to root_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :from_company, :website, :hq, :description, :banner, :url, :category_id, :company_id)
	end

	def find_jobs
		@job = Job.find(params[:id])
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    if params[:tag]
      @people = Person.tagged_with(params[:tag])
    else
      @people = Person.all
    end
  end

  def show
  end

  def crate
  end

  def new
  end

  def edit
  end

  def update
  end

  def user_params
    params.require(:person).permit(:tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>

app/views/companies/index.html.erb
<h1><%= content_for(:title, 'Company') %></h1>
<% if company_signed_in? %>
	<!-- My Jobs -->
	<% @company_jobs.each do |job|  %>
		<div class="job">
			<h2><%= link_to job.title, job %></h2>
			<p><%= job.description %></p>
			<div class="actions">
			<%= link_to "Edit", job %>
			</div>
		</div>
	<% end %>
<% else %>
	<%= link_to "Sign in", new_company_session_path %>
<% end %>

app/views/companies/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:500,400italic,300,500italic,300italic,400' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body>

<header class="site-header">
	<div class="wrapper">
		<a href="{{ site.baseurl }}" class="logo">
	      <svg version="1.1" id="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	         viewBox="0 0 295 40" enable-background="new 0 0 295 40" xml:space="preserve">
	      <g>
	        <path fill="#fff" d="M14.9,18.9l-1.9,0c-0.6,0-1.1,0.1-1.4,0.3c-0.4,0.2-0.7,0.5-0.8,0.8v10.7H5.6V14.4h4.8l0.2,2.4
	          c0.3-0.9,0.8-1.5,1.4-2c0.6-0.5,1.2-0.7,2-0.7c0.2,0,0.5,0,0.7,0.1c0.3,0,0.5,0.1,0.7,0.1L14.9,18.9z"/>
	        <path fill="#fff" d="M24.3,31.1c-2.4,0-4.3-0.8-5.8-2.3c-1.4-1.5-2.2-3.4-2.2-5.7v-0.6c0-2.5,0.7-4.5,2-6.1
	          c1.3-1.6,3.2-2.4,5.6-2.4c2.2,0,4,0.7,5.2,2c1.3,1.3,1.9,3.1,1.9,5.4v2.7h-9.4l0,0.1c0.1,0.8,0.5,1.5,1,2.1
	          c0.6,0.5,1.3,0.8,2.3,0.8c1,0,1.7-0.1,2.3-0.2c0.6-0.2,1.3-0.4,2.2-0.8l1.2,3.1c-0.7,0.5-1.6,1-2.8,1.3
	          C26.8,31,25.6,31.1,24.3,31.1z M23.9,18.1c-0.7,0-1.3,0.3-1.7,0.8c-0.4,0.5-0.6,1.2-0.7,2.1l0,0.1H26v-0.4c0-0.8-0.2-1.5-0.5-1.9
	          C25.2,18.3,24.7,18.1,23.9,18.1z"/>
	        <path fill="#fff" d="M38,14.4l0.2,2.2c0.5-0.8,1.2-1.4,1.9-1.8c0.8-0.4,1.7-0.6,2.7-0.6c1,0,1.9,0.2,2.6,0.7
	          c0.7,0.4,1.3,1.1,1.7,2c0.5-0.9,1.2-1.5,1.9-2c0.8-0.5,1.7-0.7,2.8-0.7c1.6,0,2.8,0.5,3.8,1.6c0.9,1.1,1.4,2.8,1.4,5.1v10h-5.1v-10
	          c0-1.1-0.2-1.8-0.5-2.2c-0.3-0.4-0.8-0.6-1.5-0.6c-0.5,0-0.9,0.1-1.3,0.3c-0.4,0.2-0.7,0.4-1,0.7c0,0.2,0,0.3,0,0.4
	          c0,0.1,0,0.2,0,0.4v10.9h-5.1v-10c0-1.1-0.2-1.8-0.5-2.2c-0.3-0.4-0.8-0.6-1.5-0.6c-0.5,0-0.9,0.1-1.3,0.3c-0.4,0.2-0.7,0.4-1,0.7
	          v11.7h-5.1V14.4H38z"/>
	        <path fill="#fff" d="M59.2,22.5c0-2.5,0.7-4.5,2.1-6c1.4-1.5,3.3-2.3,5.8-2.3c2.5,0,4.5,0.8,5.8,2.3c1.4,1.5,2.1,3.6,2.1,6v0.3
	          c0,2.5-0.7,4.5-2.1,6s-3.3,2.3-5.8,2.3c-2.5,0-4.5-0.8-5.9-2.3s-2.1-3.6-2.1-6V22.5z M64.3,22.8c0,1.4,0.2,2.4,0.6,3.2
	          c0.4,0.8,1.2,1.2,2.2,1.2c1,0,1.7-0.4,2.1-1.2c0.4-0.8,0.7-1.9,0.7-3.2v-0.3c0-1.3-0.2-2.4-0.7-3.2c-0.4-0.8-1.2-1.2-2.2-1.2
	          c-1,0-1.7,0.4-2.2,1.2c-0.4,0.8-0.6,1.9-0.6,3.2V22.8z"/>
	        <path fill="#fff" d="M83.4,10.4v4.1h2.8V18h-2.8v7.5c0,0.6,0.1,1,0.4,1.3c0.2,0.3,0.6,0.4,1,0.4c0.3,0,0.6,0,0.8,0
	          c0.2,0,0.4-0.1,0.7-0.1l0.4,3.8C86,30.9,85.5,31,85,31c-0.5,0.1-1,0.1-1.6,0.1c-1.7,0-3-0.4-3.8-1.3c-0.9-0.9-1.3-2.3-1.3-4.3V18
	          H76v-3.5h2.3v-4.1H83.4z"/>
	        <path fill="#fff" d="M96,31.1c-2.4,0-4.3-0.8-5.8-2.3c-1.4-1.5-2.2-3.4-2.2-5.7v-0.6c0-2.5,0.7-4.5,2-6.1
	          c1.3-1.6,3.2-2.4,5.6-2.4c2.2,0,4,0.7,5.2,2s1.9,3.1,1.9,5.4v2.7h-9.4l0,0.1c0.1,0.8,0.5,1.5,1,2.1c0.6,0.5,1.3,0.8,2.3,0.8
	          c1,0,1.7-0.1,2.3-0.2c0.6-0.2,1.3-0.4,2.2-0.8l1.2,3.1c-0.7,0.5-1.6,1-2.8,1.3C98.6,31,97.3,31.1,96,31.1z M95.7,18.1
	          c-0.7,0-1.3,0.3-1.7,0.8c-0.4,0.5-0.6,1.2-0.7,2.1l0,0.1h4.4v-0.4c0-0.8-0.2-1.5-0.5-1.9C96.9,18.3,96.4,18.1,95.7,18.1z"/>
	        <path fill="#fff" d="M117.2,34.6h-13.7v-3.8h13.7V34.6z"/>
	        <path fill="#fff" d="M118,22.7c0-2.6,0.6-4.6,1.7-6.2c1.1-1.6,2.7-2.3,4.7-2.3c0.8,0,1.4,0.2,2.1,0.5c0.6,0.3,1.2,0.8,1.6,1.5
	          V7.2h5.1v23.6h-4.4l-0.4-2c-0.5,0.8-1.1,1.3-1.8,1.7c-0.7,0.4-1.4,0.6-2.3,0.6c-2,0-3.6-0.7-4.7-2.2c-1.1-1.5-1.7-3.5-1.7-5.9V22.7
	          z M123.1,23c0,1.3,0.2,2.4,0.6,3.1c0.4,0.7,1,1.1,2,1.1c0.5,0,1-0.1,1.4-0.3c0.4-0.2,0.7-0.5,1-0.9v-6.6c-0.3-0.4-0.6-0.8-1-1
	          c-0.4-0.2-0.9-0.3-1.4-0.3c-0.9,0-1.6,0.4-2,1.3c-0.4,0.8-0.6,1.9-0.6,3.3V23z"/>
	        <path fill="#fff" d="M143.5,31.1c-2.4,0-4.3-0.8-5.8-2.3c-1.4-1.5-2.2-3.4-2.2-5.7v-0.6c0-2.5,0.7-4.5,2-6.1
	          c1.3-1.6,3.2-2.4,5.6-2.4c2.2,0,4,0.7,5.2,2c1.3,1.3,1.9,3.1,1.9,5.4v2.7h-9.4l0,0.1c0.1,0.8,0.5,1.5,1,2.1
	          c0.6,0.5,1.3,0.8,2.3,0.8c1,0,1.7-0.1,2.3-0.2s1.3-0.4,2.2-0.8l1.2,3.1c-0.7,0.5-1.6,1-2.8,1.3C146.1,31,144.8,31.1,143.5,31.1z
	           M143.2,18.1c-0.7,0-1.3,0.3-1.7,0.8c-0.4,0.5-0.6,1.2-0.7,2.1l0,0.1h4.4v-0.4c0-0.8-0.2-1.5-0.5-1.9
	          C144.4,18.3,143.9,18.1,143.2,18.1z"/>
	        <path fill="#fff" d="M167.6,23c0,2.5-0.6,4.4-1.7,5.9c-1.1,1.5-2.7,2.2-4.7,2.2c-0.8,0-1.5-0.2-2.1-0.5s-1.1-0.7-1.6-1.3v7.8
	          h-5.1V14.4h4.8l0.2,1.8c0.5-0.7,1-1.2,1.6-1.6s1.4-0.5,2.2-0.5c2,0,3.6,0.8,4.7,2.3c1.1,1.6,1.7,3.6,1.7,6.2V23z M162.5,22.7
	          c0-1.4-0.2-2.5-0.6-3.3c-0.4-0.8-1-1.3-1.9-1.3c-0.6,0-1.1,0.1-1.5,0.3c-0.4,0.2-0.7,0.5-0.9,0.9v6.8c0.2,0.4,0.6,0.6,1,0.8
	          c0.4,0.2,0.9,0.3,1.5,0.3c0.9,0,1.5-0.4,1.9-1.1c0.4-0.7,0.6-1.8,0.6-3.1V22.7z"/>
	        <path fill="#fff" d="M179.3,30.8c-0.1-0.3-0.3-0.6-0.4-0.9c-0.1-0.3-0.2-0.7-0.3-1c-0.5,0.7-1.1,1.2-1.8,1.6
	          c-0.7,0.4-1.5,0.6-2.5,0.6c-1.6,0-2.8-0.4-3.8-1.3c-1-0.9-1.5-2.1-1.5-3.6c0-1.6,0.6-2.9,1.8-3.8c1.2-0.9,3.1-1.3,5.5-1.3h1.9v-1.2
	          c0-0.7-0.2-1.2-0.5-1.6c-0.3-0.4-0.8-0.6-1.5-0.6c-0.6,0-1,0.1-1.3,0.4c-0.3,0.3-0.4,0.7-0.4,1.3l-4.9,0l0-0.1
	          c-0.1-1.5,0.5-2.7,1.9-3.7c1.3-1,3-1.5,5.2-1.5c2,0,3.7,0.5,4.9,1.5c1.3,1,1.9,2.5,1.9,4.3v6.2c0,0.9,0.1,1.7,0.2,2.4
	          c0.1,0.7,0.4,1.5,0.7,2.2L179.3,30.8z M175.9,27.5c0.5,0,1-0.1,1.4-0.3c0.4-0.2,0.8-0.5,1-0.8v-2.6h-1.8c-0.8,0-1.4,0.2-1.8,0.6
	          c-0.4,0.4-0.6,0.9-0.6,1.5c0,0.5,0.2,0.8,0.5,1.1C175,27.3,175.4,27.5,175.9,27.5z"/>
	        <path fill="#fff" d="M195.6,18.9l-1.9,0c-0.6,0-1.1,0.1-1.4,0.3c-0.4,0.2-0.7,0.5-0.8,0.8v10.7h-5.1V14.4h4.8l0.2,2.4
	          c0.3-0.9,0.8-1.5,1.4-2c0.6-0.5,1.2-0.7,2-0.7c0.2,0,0.5,0,0.7,0.1c0.3,0,0.5,0.1,0.7,0.1L195.6,18.9z"/>
	        <path fill="#fff" d="M204.2,10.4v4.1h2.8V18h-2.8v7.5c0,0.6,0.1,1,0.4,1.3c0.2,0.3,0.6,0.4,1,0.4c0.3,0,0.6,0,0.8,0
	          c0.2,0,0.4-0.1,0.7-0.1l0.4,3.8c-0.6,0.1-1.1,0.2-1.5,0.3c-0.5,0.1-1,0.1-1.6,0.1c-1.7,0-3-0.4-3.8-1.3c-0.9-0.9-1.3-2.3-1.3-4.3
	          V18h-2.3v-3.5h2.3v-4.1H204.2z"/>
	        <path fill="#fff" d="M214.2,14.4l0.2,2.2c0.5-0.8,1.2-1.4,1.9-1.8c0.8-0.4,1.7-0.6,2.7-0.6c1,0,1.9,0.2,2.6,0.7
	          c0.7,0.4,1.3,1.1,1.7,2c0.5-0.9,1.2-1.5,1.9-2c0.8-0.5,1.7-0.7,2.8-0.7c1.6,0,2.8,0.5,3.8,1.6c0.9,1.1,1.4,2.8,1.4,5.1v10H228v-10
	          c0-1.1-0.2-1.8-0.5-2.2s-0.8-0.6-1.5-0.6c-0.5,0-0.9,0.1-1.3,0.3c-0.4,0.2-0.7,0.4-1,0.7c0,0.2,0,0.3,0,0.4c0,0.1,0,0.2,0,0.4v10.9
	          h-5.1v-10c0-1.1-0.2-1.8-0.5-2.2s-0.8-0.6-1.5-0.6c-0.5,0-0.9,0.1-1.3,0.3c-0.4,0.2-0.7,0.4-1,0.7v11.7h-5.1V14.4H214.2z"/>
	        <path fill="#fff" d="M243.5,31.1c-2.4,0-4.3-0.8-5.8-2.3c-1.4-1.5-2.2-3.4-2.2-5.7v-0.6c0-2.5,0.7-4.5,2-6.1
	          c1.3-1.6,3.2-2.4,5.6-2.4c2.2,0,4,0.7,5.2,2c1.3,1.3,1.9,3.1,1.9,5.4v2.7h-9.4l0,0.1c0.1,0.8,0.5,1.5,1,2.1
	          c0.6,0.5,1.3,0.8,2.3,0.8c1,0,1.7-0.1,2.3-0.2s1.3-0.4,2.2-0.8l1.2,3.1c-0.7,0.5-1.6,1-2.8,1.3C246.1,31,244.8,31.1,243.5,31.1z
	           M243.2,18.1c-0.7,0-1.3,0.3-1.7,0.8c-0.4,0.5-0.6,1.2-0.7,2.1l0,0.1h4.4v-0.4c0-0.8-0.2-1.5-0.5-1.9
	          C244.4,18.3,243.9,18.1,243.2,18.1z"/>
	        <path fill="#fff" d="M257.2,14.4l0.2,2.3c0.5-0.8,1.2-1.5,2-1.9c0.8-0.5,1.7-0.7,2.6-0.7c1.6,0,2.9,0.5,3.8,1.6
	          c0.9,1,1.4,2.7,1.4,5v10.2H262V20.6c0-0.9-0.2-1.6-0.6-2c-0.4-0.4-1-0.6-1.7-0.6c-0.5,0-0.9,0.1-1.3,0.3c-0.4,0.2-0.7,0.4-0.9,0.7
	          v11.8h-5.1V14.4H257.2z"/>
	        <path fill="#fff" d="M275.9,10.4v4.1h2.8V18h-2.8v7.5c0,0.6,0.1,1,0.4,1.3c0.2,0.3,0.6,0.4,1,0.4c0.3,0,0.6,0,0.8,0
	          c0.2,0,0.4-0.1,0.7-0.1l0.4,3.8c-0.6,0.1-1.1,0.2-1.5,0.3c-0.5,0.1-1,0.1-1.6,0.1c-1.7,0-3-0.4-3.8-1.3c-0.9-0.9-1.3-2.3-1.3-4.3
	          V18h-2.3v-3.5h2.3v-4.1H275.9z"/>
	      </g>
	      <g>
	        <path fill="#fff" d="M285.7,4.4h-2.4V11h-0.6V4.4h-2.4V3.9h5.5V4.4z"/>
	        <path fill="#fff" d="M287.6,3.9l2.6,6.3h0l2.6-6.3h0.8V11h-0.6V7.9l0-3.1l0,0l-2.6,6.3H290l-2.6-6.2l0,0l0.1,3.1V11h-0.6V3.9
	          H287.6z"/>
	      </g>
	      </svg>
	    </a>
		<nav class="navigation">
			<ul>
				<li><%= link_to "All Jobs", jobs_path %></li>
				<li><%= link_to "People", people_index_path %></li>
				<li><%= link_to "Companies", companies_index_path %></li>
			</ul>
		</nav>
		<ul class="login">
			<% if company_signed_in? %>
				<li>Hey, <span><%= current_company.email %></span></li>
				<li><%= link_to "Sign out", destroy_company_session_path, method: :delete, :class => "btn btn-default" %></li>
			<% elsif person_signed_in? %>
				<li>
					<span class="name">Hey, <%= current_person.name %></span>
					<span class="img_holder"><img src="/images/default_talent.jpg" /></span>
					<ul>
						
						<li><%= link_to "Sign out", destroy_person_session_path, method: :delete, :class => "btn btn-default" %></li>
					</ul>
					
				</li>
			<% else %>
				<li><%= link_to "Login", companies_index_path %></li>
				<li><%= link_to "Companies", companies_index_path %></li>
			<% end %>

		</ul>
	</div>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/people/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>